// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateItem = `-- name: CreateItem :one
INSERT INTO items (
  user_id, name, category, price, brand, color, season,
  image_url, notes, wear_count, ai_analysis, tags
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, user_id, name, category, price, brand, color, season, image_url, notes, wear_count, ai_analysis, tags, uploaded_at, created_at, updated_at
`

type CreateItemParams struct {
	UserID     pgtype.Int8    `json:"user_id"`
	Name       string         `json:"name"`
	Category   string         `json:"category"`
	Price      pgtype.Numeric `json:"price"`
	Brand      pgtype.Text    `json:"brand"`
	Color      pgtype.Text    `json:"color"`
	Season     pgtype.Text    `json:"season"`
	ImageUrl   string         `json:"image_url"`
	Notes      pgtype.Text    `json:"notes"`
	WearCount  pgtype.Int4    `json:"wear_count"`
	AiAnalysis pgtype.Text    `json:"ai_analysis"`
	Tags       []string       `json:"tags"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, CreateItem,
		arg.UserID,
		arg.Name,
		arg.Category,
		arg.Price,
		arg.Brand,
		arg.Color,
		arg.Season,
		arg.ImageUrl,
		arg.Notes,
		arg.WearCount,
		arg.AiAnalysis,
		arg.Tags,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Category,
		&i.Price,
		&i.Brand,
		&i.Color,
		&i.Season,
		&i.ImageUrl,
		&i.Notes,
		&i.WearCount,
		&i.AiAnalysis,
		&i.Tags,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteItem = `-- name: DeleteItem :exec
DELETE FROM items
WHERE id = $1 AND user_id = $2
`

type DeleteItemParams struct {
	ID     int64       `json:"id"`
	UserID pgtype.Int8 `json:"user_id"`
}

func (q *Queries) DeleteItem(ctx context.Context, arg DeleteItemParams) error {
	_, err := q.db.Exec(ctx, DeleteItem, arg.ID, arg.UserID)
	return err
}

const GetItem = `-- name: GetItem :one
SELECT id, user_id, name, category, price, brand, color, season, image_url, notes, wear_count, ai_analysis, tags, uploaded_at, created_at, updated_at FROM items
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetItemParams struct {
	ID     int64       `json:"id"`
	UserID pgtype.Int8 `json:"user_id"`
}

func (q *Queries) GetItem(ctx context.Context, arg GetItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, GetItem, arg.ID, arg.UserID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Category,
		&i.Price,
		&i.Brand,
		&i.Color,
		&i.Season,
		&i.ImageUrl,
		&i.Notes,
		&i.WearCount,
		&i.AiAnalysis,
		&i.Tags,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const IncrementWearCount = `-- name: IncrementWearCount :exec
UPDATE items
SET wear_count = wear_count + 1
WHERE id = $1
`

func (q *Queries) IncrementWearCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, IncrementWearCount, id)
	return err
}

const ListItems = `-- name: ListItems :many
SELECT id, user_id, name, category, price, brand, color, season, image_url, notes, wear_count, ai_analysis, tags, uploaded_at, created_at, updated_at FROM items
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListItems(ctx context.Context, userID pgtype.Int8) ([]Item, error) {
	rows, err := q.db.Query(ctx, ListItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Category,
			&i.Price,
			&i.Brand,
			&i.Color,
			&i.Season,
			&i.ImageUrl,
			&i.Notes,
			&i.WearCount,
			&i.AiAnalysis,
			&i.Tags,
			&i.UploadedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListItemsByCategory = `-- name: ListItemsByCategory :many
SELECT id, user_id, name, category, price, brand, color, season, image_url, notes, wear_count, ai_analysis, tags, uploaded_at, created_at, updated_at FROM items
WHERE user_id = $1 AND category = $2
ORDER BY created_at DESC
`

type ListItemsByCategoryParams struct {
	UserID   pgtype.Int8 `json:"user_id"`
	Category string      `json:"category"`
}

func (q *Queries) ListItemsByCategory(ctx context.Context, arg ListItemsByCategoryParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, ListItemsByCategory, arg.UserID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Category,
			&i.Price,
			&i.Brand,
			&i.Color,
			&i.Season,
			&i.ImageUrl,
			&i.Notes,
			&i.WearCount,
			&i.AiAnalysis,
			&i.Tags,
			&i.UploadedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateItem = `-- name: UpdateItem :one
UPDATE items
SET name = $2,
    category = $3,
    price = $4,
    brand = $5,
    color = $6,
    season = $7,
    notes = $8,
    ai_analysis = $9,
    tags = $10,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, category, price, brand, color, season, image_url, notes, wear_count, ai_analysis, tags, uploaded_at, created_at, updated_at
`

type UpdateItemParams struct {
	ID         int64          `json:"id"`
	Name       string         `json:"name"`
	Category   string         `json:"category"`
	Price      pgtype.Numeric `json:"price"`
	Brand      pgtype.Text    `json:"brand"`
	Color      pgtype.Text    `json:"color"`
	Season     pgtype.Text    `json:"season"`
	Notes      pgtype.Text    `json:"notes"`
	AiAnalysis pgtype.Text    `json:"ai_analysis"`
	Tags       []string       `json:"tags"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, UpdateItem,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.Price,
		arg.Brand,
		arg.Color,
		arg.Season,
		arg.Notes,
		arg.AiAnalysis,
		arg.Tags,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Category,
		&i.Price,
		&i.Brand,
		&i.Color,
		&i.Season,
		&i.ImageUrl,
		&i.Notes,
		&i.WearCount,
		&i.AiAnalysis,
		&i.Tags,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
