// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CalendarEvent struct {
	ID        int64            `json:"id"`
	UserID    pgtype.Int8      `json:"user_id"`
	EventDate pgtype.Date      `json:"event_date"`
	EventName pgtype.Text      `json:"event_name"`
	Weather   pgtype.Text      `json:"weather"`
	OutfitID  pgtype.Int8      `json:"outfit_id"`
	Notes     pgtype.Text      `json:"notes"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Item struct {
	ID         int64            `json:"id"`
	UserID     pgtype.Int8      `json:"user_id"`
	Name       string           `json:"name"`
	Category   string           `json:"category"`
	Price      pgtype.Numeric   `json:"price"`
	Brand      pgtype.Text      `json:"brand"`
	Color      pgtype.Text      `json:"color"`
	Season     pgtype.Text      `json:"season"`
	ImageUrl   string           `json:"image_url"`
	Notes      pgtype.Text      `json:"notes"`
	WearCount  pgtype.Int4      `json:"wear_count"`
	AiAnalysis pgtype.Text      `json:"ai_analysis"`
	Tags       []string         `json:"tags"`
	UploadedAt pgtype.Timestamp `json:"uploaded_at"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type Outfit struct {
	ID           int64            `json:"id"`
	UserID       pgtype.Int8      `json:"user_id"`
	Name         string           `json:"name"`
	Notes        pgtype.Text      `json:"notes"`
	WearCount    pgtype.Int4      `json:"wear_count"`
	Rating       pgtype.Numeric   `json:"rating"`
	BodyImageUrl pgtype.Text      `json:"body_image_url"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type OutfitItem struct {
	ID        int64            `json:"id"`
	OutfitID  pgtype.Int8      `json:"outfit_id"`
	ItemID    pgtype.Int8      `json:"item_id"`
	PositionX pgtype.Int4      `json:"position_x"`
	PositionY pgtype.Int4      `json:"position_y"`
	PositionZ pgtype.Int4      `json:"position_z"`
	Scale     pgtype.Numeric   `json:"scale"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type OutfitRating struct {
	ID       int64            `json:"id"`
	OutfitID pgtype.Int8      `json:"outfit_id"`
	Rating   pgtype.Int4      `json:"rating"`
	RatedAt  pgtype.Timestamp `json:"rated_at"`
}

type SharedOutfit struct {
	ID        int64            `json:"id"`
	OutfitID  pgtype.Int8      `json:"outfit_id"`
	ShareID   string           `json:"share_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Views     pgtype.Int4      `json:"views"`
}

type User struct {
	ID        int64            `json:"id"`
	Email     string           `json:"email"`
	Name      pgtype.Text      `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type UserSetting struct {
	UserID                int64            `json:"user_id"`
	AutoRemoveBg          pgtype.Bool      `json:"auto_remove_bg"`
	AutoTag               pgtype.Bool      `json:"auto_tag"`
	AiProvider            pgtype.Text      `json:"ai_provider"`
	Currency              pgtype.Text      `json:"currency"`
	DateFormat            pgtype.Text      `json:"date_format"`
	MaxWearsBeforeLaundry pgtype.Int4      `json:"max_wears_before_laundry"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
}

type WearHistory struct {
	ID       int64            `json:"id"`
	UserID   pgtype.Int8      `json:"user_id"`
	ItemID   pgtype.Int8      `json:"item_id"`
	OutfitID pgtype.Int8      `json:"outfit_id"`
	WornAt   pgtype.Timestamp `json:"worn_at"`
}
