// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outfits.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const AddItemToOutfit = `-- name: AddItemToOutfit :one
INSERT INTO outfit_items (
  outfit_id, item_id, position_x, position_y, position_z, scale
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, outfit_id, item_id, position_x, position_y, position_z, scale, created_at
`

type AddItemToOutfitParams struct {
	OutfitID  pgtype.Int8    `json:"outfit_id"`
	ItemID    pgtype.Int8    `json:"item_id"`
	PositionX pgtype.Int4    `json:"position_x"`
	PositionY pgtype.Int4    `json:"position_y"`
	PositionZ pgtype.Int4    `json:"position_z"`
	Scale     pgtype.Numeric `json:"scale"`
}

func (q *Queries) AddItemToOutfit(ctx context.Context, arg AddItemToOutfitParams) (OutfitItem, error) {
	row := q.db.QueryRow(ctx, AddItemToOutfit,
		arg.OutfitID,
		arg.ItemID,
		arg.PositionX,
		arg.PositionY,
		arg.PositionZ,
		arg.Scale,
	)
	var i OutfitItem
	err := row.Scan(
		&i.ID,
		&i.OutfitID,
		&i.ItemID,
		&i.PositionX,
		&i.PositionY,
		&i.PositionZ,
		&i.Scale,
		&i.CreatedAt,
	)
	return i, err
}

const CreateOutfit = `-- name: CreateOutfit :one
INSERT INTO outfits (
  user_id, name, notes, wear_count, rating, body_image_url
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, name, notes, wear_count, rating, body_image_url, created_at, updated_at
`

type CreateOutfitParams struct {
	UserID       pgtype.Int8    `json:"user_id"`
	Name         string         `json:"name"`
	Notes        pgtype.Text    `json:"notes"`
	WearCount    pgtype.Int4    `json:"wear_count"`
	Rating       pgtype.Numeric `json:"rating"`
	BodyImageUrl pgtype.Text    `json:"body_image_url"`
}

func (q *Queries) CreateOutfit(ctx context.Context, arg CreateOutfitParams) (Outfit, error) {
	row := q.db.QueryRow(ctx, CreateOutfit,
		arg.UserID,
		arg.Name,
		arg.Notes,
		arg.WearCount,
		arg.Rating,
		arg.BodyImageUrl,
	)
	var i Outfit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Notes,
		&i.WearCount,
		&i.Rating,
		&i.BodyImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteOutfit = `-- name: DeleteOutfit :exec
DELETE FROM outfits
WHERE id = $1 AND user_id = $2
`

type DeleteOutfitParams struct {
	ID     int64       `json:"id"`
	UserID pgtype.Int8 `json:"user_id"`
}

func (q *Queries) DeleteOutfit(ctx context.Context, arg DeleteOutfitParams) error {
	_, err := q.db.Exec(ctx, DeleteOutfit, arg.ID, arg.UserID)
	return err
}

const DeleteOutfitItems = `-- name: DeleteOutfitItems :exec
DELETE FROM outfit_items
WHERE outfit_id = $1
`

func (q *Queries) DeleteOutfitItems(ctx context.Context, outfitID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, DeleteOutfitItems, outfitID)
	return err
}

const GetOutfit = `-- name: GetOutfit :one
SELECT id, user_id, name, notes, wear_count, rating, body_image_url, created_at, updated_at FROM outfits
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetOutfitParams struct {
	ID     int64       `json:"id"`
	UserID pgtype.Int8 `json:"user_id"`
}

func (q *Queries) GetOutfit(ctx context.Context, arg GetOutfitParams) (Outfit, error) {
	row := q.db.QueryRow(ctx, GetOutfit, arg.ID, arg.UserID)
	var i Outfit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Notes,
		&i.WearCount,
		&i.Rating,
		&i.BodyImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetOutfitItems = `-- name: GetOutfitItems :many
SELECT oi.id, oi.outfit_id, oi.item_id, oi.position_x, oi.position_y, oi.position_z, oi.scale, oi.created_at, i.id, i.user_id, i.name, i.category, i.price, i.brand, i.color, i.season, i.image_url, i.notes, i.wear_count, i.ai_analysis, i.tags, i.uploaded_at, i.created_at, i.updated_at
FROM outfit_items oi
JOIN items i ON i.id = oi.item_id
WHERE oi.outfit_id = $1
ORDER BY oi.position_z ASC
`

type GetOutfitItemsRow struct {
	ID          int64            `json:"id"`
	OutfitID    pgtype.Int8      `json:"outfit_id"`
	ItemID      pgtype.Int8      `json:"item_id"`
	PositionX   pgtype.Int4      `json:"position_x"`
	PositionY   pgtype.Int4      `json:"position_y"`
	PositionZ   pgtype.Int4      `json:"position_z"`
	Scale       pgtype.Numeric   `json:"scale"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	ID_2        int64            `json:"id_2"`
	UserID      pgtype.Int8      `json:"user_id"`
	Name        string           `json:"name"`
	Category    string           `json:"category"`
	Price       pgtype.Numeric   `json:"price"`
	Brand       pgtype.Text      `json:"brand"`
	Color       pgtype.Text      `json:"color"`
	Season      pgtype.Text      `json:"season"`
	ImageUrl    string           `json:"image_url"`
	Notes       pgtype.Text      `json:"notes"`
	WearCount   pgtype.Int4      `json:"wear_count"`
	AiAnalysis  pgtype.Text      `json:"ai_analysis"`
	Tags        []string         `json:"tags"`
	UploadedAt  pgtype.Timestamp `json:"uploaded_at"`
	CreatedAt_2 pgtype.Timestamp `json:"created_at_2"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetOutfitItems(ctx context.Context, outfitID pgtype.Int8) ([]GetOutfitItemsRow, error) {
	rows, err := q.db.Query(ctx, GetOutfitItems, outfitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOutfitItemsRow{}
	for rows.Next() {
		var i GetOutfitItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OutfitID,
			&i.ItemID,
			&i.PositionX,
			&i.PositionY,
			&i.PositionZ,
			&i.Scale,
			&i.CreatedAt,
			&i.ID_2,
			&i.UserID,
			&i.Name,
			&i.Category,
			&i.Price,
			&i.Brand,
			&i.Color,
			&i.Season,
			&i.ImageUrl,
			&i.Notes,
			&i.WearCount,
			&i.AiAnalysis,
			&i.Tags,
			&i.UploadedAt,
			&i.CreatedAt_2,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const IncrementOutfitWearCount = `-- name: IncrementOutfitWearCount :exec
UPDATE outfits
SET wear_count = wear_count + 1
WHERE id = $1
`

func (q *Queries) IncrementOutfitWearCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, IncrementOutfitWearCount, id)
	return err
}

const ListOutfits = `-- name: ListOutfits :many
SELECT id, user_id, name, notes, wear_count, rating, body_image_url, created_at, updated_at FROM outfits
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOutfits(ctx context.Context, userID pgtype.Int8) ([]Outfit, error) {
	rows, err := q.db.Query(ctx, ListOutfits, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outfit{}
	for rows.Next() {
		var i Outfit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Notes,
			&i.WearCount,
			&i.Rating,
			&i.BodyImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateOutfit = `-- name: UpdateOutfit :one
UPDATE outfits
SET name = $2,
    notes = $3,
    rating = $4,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, notes, wear_count, rating, body_image_url, created_at, updated_at
`

type UpdateOutfitParams struct {
	ID     int64          `json:"id"`
	Name   string         `json:"name"`
	Notes  pgtype.Text    `json:"notes"`
	Rating pgtype.Numeric `json:"rating"`
}

func (q *Queries) UpdateOutfit(ctx context.Context, arg UpdateOutfitParams) (Outfit, error) {
	row := q.db.QueryRow(ctx, UpdateOutfit,
		arg.ID,
		arg.Name,
		arg.Notes,
		arg.Rating,
	)
	var i Outfit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Notes,
		&i.WearCount,
		&i.Rating,
		&i.BodyImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
