// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddItemToOutfit(ctx context.Context, arg AddItemToOutfitParams) (OutfitItem, error)
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	CreateOutfit(ctx context.Context, arg CreateOutfitParams) (Outfit, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteItem(ctx context.Context, arg DeleteItemParams) error
	DeleteOutfit(ctx context.Context, arg DeleteOutfitParams) error
	DeleteOutfitItems(ctx context.Context, outfitID pgtype.Int8) error
	GetItem(ctx context.Context, arg GetItemParams) (Item, error)
	GetOutfit(ctx context.Context, arg GetOutfitParams) (Outfit, error)
	GetOutfitItems(ctx context.Context, outfitID pgtype.Int8) ([]GetOutfitItemsRow, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	IncrementOutfitWearCount(ctx context.Context, id int64) error
	IncrementWearCount(ctx context.Context, id int64) error
	ListItems(ctx context.Context, userID pgtype.Int8) ([]Item, error)
	ListItemsByCategory(ctx context.Context, arg ListItemsByCategoryParams) ([]Item, error)
	ListOutfits(ctx context.Context, userID pgtype.Int8) ([]Outfit, error)
	UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error)
	UpdateOutfit(ctx context.Context, arg UpdateOutfitParams) (Outfit, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
